- hosts: terraform.greatcatinternal.net
  tasks:
    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes
  
    - name: Run awscli install script
      script: ../awscli.sh  
